"""Migração inicial da base de dados

Revision ID: b7baef00f196
Revises: 
Create Date: 2025-08-18 12:26:33.351808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7baef00f196'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('preco_aluguel', sa.Float(), nullable=True),
    sa.Column('total_copias', sa.Integer(), nullable=True),
    sa.Column('copias_disponiveis', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filmes_id'), 'filmes', ['id'], unique=False)
    op.create_index(op.f('ix_filmes_titulo'), 'filmes', ['titulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filmes_titulo'), table_name='filmes')
    op.drop_index(op.f('ix_filmes_id'), table_name='filmes')
    op.drop_table('filmes')
    # ### end Alembic commands ###
