spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: auth-service
            uri: http://localhost:8081
            predicates:
              - Path=/auth/**
            filters:
              - StripPrefix=1

          - id: rent-service
            uri: http://localhost:8001
            predicates:
              - Path=/rent/**
            filters:
              - StripPrefix=1

          - id: user-service
            uri: http://localhost:8002
            predicates:
              - Path=/user/**
            filters:
              - StripPrefix=1

          - id: payment-service
            uri: http://localhost:8005
            predicates:
              - Path=/payment/**
            filters:
              - StripPrefix=1

          - id: movie-service
            uri: http://localhost:8000
            predicates:
              - Path=/movie/**
            filters:
              - StripPrefix=1