sonar.projectKey=looker-payment-service
sonar.projectName=Looker - Payment Service
sonar.sources=app
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.exclusions=**/__pycache__/**
