"""Cria tabela de alugueis

Revision ID: c5652286aef9
Revises: 
Create Date: 2025-08-19 11:27:46.406000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5652286aef9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alugueis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filme_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_aluguel', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_prevista_devolucao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_devolucao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valor_aluguel', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'DEVOLVIDO', 'ATRASADO', name='aluguelstatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alugueis_id'), 'alugueis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alugueis_id'), table_name='alugueis')
    op.drop_table('alugueis')
    # ### end Alembic commands ###
